export 'presentation/views/watchlist_view.dart';
export 'domain/repo/watch_list_repo.dart';
export 'domain/usecase/add_to_Watchlist_usecase.dart';
export 'presentation/notifier/add_to_watch_list_notifier.dart';
export 'watchlist_locator.dart';
export  'presentation/notifier/get_watch_list_movie_id_notifier.dart';
export 'data/datasource/watch_list_data_source.dart';
export 'data/repo-impl/watch_list_repo_impl.dart';
export 'domain/usecase/get_watchlist_movie_id_usecase.dart';
export 'domain/usecase/watchlist_movie_details.dart';
export  'presentation/notifier/watch_list_details_notifier.dart';
export 'presentation/widgets/watch_list_body_widget.dart';
export 'domain/usecase/remove_from_watch_list_usecase.dart';
export 'presentation/notifier/remove_movie_from watchlist.dart';
